[package]
name = "chrome-pdf-viewer"
version = "0.1.0"
authors = ["maxloh <35831069+maxloh@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.1.1"
